#TODO:
1. output failing test properly
2. check if exit with nonzero when test failed

#Bug:

1. Only put 2 into failedResult when all 3 are failing
2. test_runner didnt terminate nicely

